apiVersion: v1
kind: Service
metadata:
  name: mysql-server-svc
  namespace: {{ .Spec.Namespace }}
spec:
  ports:
    - name: mysql
      {{ if .Spec.EnableNodePort -}}
      nodePort: 3306
      {{ end -}}
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  {{ if .Spec.EnableNodePort -}}
  type: NodePort
  {{ else -}}
  type: ClusterIP
  {{- end -}}