apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: base-builder
    meta.helm.sh/release-namespace: component
  creationTimestamp: "2024-03-27T15:51:39Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: redis-server-svc
  namespace: component
  resourceVersion: "212763"
  uid: 7bc92bdc-4d93-4622-82c5-13bb2a497a39
spec:
  clusterIP: 10.43.136.103
  clusterIPs:
  - 10.43.136.103
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis
    nodePort: 6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
