apiVersion: v1
data:
  kafka_acl_password: {{ b64enc .Spec.LoginPass }}
  kafka_acl_username: {{ b64enc .Spec.LoginUser }}
kind: Secret
metadata:
  name: kafka-auth
  namespace: {{ .Spec.Namespace }}
type: Opaque